package minesweeper.tiles;

public enum TileType{
    NUMBER_0, 
    NUMBER_1,
    NUMBER_2, 
    NUMBER_3,
    NUMBER_4, 
    NUMBER_5,
    NUMBER_6, 
    NUMBER_7,
    NUMBER_8, 
    NUMBER_9,
    NUMBER_NULL, 
    NUMBER_MINUS,
    SMILE,
    PRESSED_SMILE,
    SHOCKED_FACE,
    SUNGLASSES_FACE,
    SAD_FACE,
    COVERED_TILE,
    EMPTY_TILE,
    FLAG,
    UNTRIGGERED_MINE,
    TRIGGERED_MINE,
    MINE_ERROR,
    TILE_1,
    TILE_2,
    TILE_3,
    TILE_4,
    TILE_5,
    TILE_6,
    TILE_7,
    TILE_8
}
